name: Test

on:
  push:
    branches: ["master", "dev", "autotest"]
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'test/**'
      - 'Project.toml'
  pull_request:
    branches: ["master", "dev"]
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'test/**'
      - 'Project.toml'

permissions:
  actions: write
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.x]
        julia-arch: [x64]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SOLPSTESTSAMPLES_SSH_KEY}}
            ${{ secrets.DVC_SSH_KEY }}
      - name: Configure ssh
        run: |
          echo "${{ secrets.DVC_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.DVC_SSH_CONFIG }}" >> ~/.ssh/config
      - uses: iterative/setup-dvc@v1
      - name: DVC Pull
        run: |
          dvc pull
      - uses: julia-actions/cache@v1
      - name: "Add the FuseRegistry via Git"
        run: |
          julia --project=. -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url="https://github.com/ProjectTorreyPines/FuseRegistry.jl.git")); Pkg.Registry.add("General")'
      - uses: julia-actions/julia-runtest@v1
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: test_result_images
          path: test/*.png
      # Not set up yet
      # - uses: julia-actions/julia-processcoverage@v1
      # - uses: codecov/codecov-action@v4
      #   with:
      #     files: lcov.info